title: Radosław Daniluk
description: <a href="https://rdaniluk.pl">rdaniluk.pl</a>
show_downloads:
google_analytics:
theme: jekyll-theme-minimal

head_pic: portret.png
projects_url: "https://github.com/radek-daniluk"
github_url: "https://github.com/radek-daniluk"
